# Qt
FIND_PACKAGE(Qt4 REQUIRED)
INCLUDE(${QT_USE_FILE})

# OpenGL
FIND_PACKAGE(OpenGL REQUIRED)

# Global
SET(MEDIA_LIBRARIES
    ${QT_LIBRARIES}
	${OPENGL_LIBRARIES}
    CellarWorkbench)
SET(MEDIA_INCLUDE_DIR 
	${CELLAR_INCLUDE_DIR}
    ${MEDIA_INCLUDE_DIR})
