# Qt
FIND_PACKAGE(Qt5Core REQUIRED)
FIND_PACKAGE(Qt5Gui REQUIRED)
SET(CMAKE_AUTOMOC ON)


# Global
SET(MEDIA_LIBRARIES
    ${CELLAR_PROJECT}
    ${GL3_PROJECT})
SET(MEDIA_INCLUDE_DIR 
    ${CELLAR_SRC_DIR}
    ${MEDIA_SRC_DIR}
    ${EXTH_OTS_DIR})
SET(MEDIA_QT_MODULES
    Core
    Gui)
