# Qt
FIND_PACKAGE(Qt4 REQUIRED)
SET(QT_USE_QTOPENGL TRUE)
INCLUDE(${QT_USE_FILE})


# Glew
FIND_PACKAGE(GLEW REQUIRED)
MESSAGE(STATUS "GLEW bin: ${GLEW_LIBRARY}")
MESSAGE(STATUS "GLEW inc: ${GLEW_INCLUDE_PATH}")


# Global
SET(SCAENA_LIBRARIES
    CellarWorkbench
    PropRoom2D
    PropRoom3D
	${GLEW_LIBRARY}
	${GLEW_LIBRARIES})
SET(SCAENA_INCLUDE_DIR 
	${SCAENA_INCLUDE_DIR} 
	${GLEW_INCLUDE_PATH})
