# Qt
FIND_PACKAGE(Qt4 REQUIRED)
SET(QT_USE_QTOPENGL TRUE)
INCLUDE(${QT_USE_FILE})

# Global
SET(SCAENA_LIBRARIES
    ${QT_LIBRARIES}
    CellarWorkbench
    MediaWorkbench
    PropRoom2D)
SET(SCAENA_INCLUDE_DIR
    ${CELLAR_INCLUDE_DIR}
	${MEDIA_INCLUDE_DIR}
    ${PROP2_INCLUDE_DIR}
    ${SCAENA_INCLUDE_DIR})