# Qt
FIND_PACKAGE(Qt5Widgets REQUIRED)
FIND_PACKAGE(Qt5OpenGL REQUIRED)
SET(CMAKE_AUTOMOC ON)


# Global
SET(SCAENA_LIBRARIES
    ${CELLAR_PROJECT}
    ${MEDIA_PROJECT}
    ${PROP2_PROJECT}
    ${PROP3_PROJECT})
SET(SCAENA_INCLUDE_DIR
    ${CELLAR_SRC_DIR}
    ${MEDIA_SRC_DIR}
    ${PROP2_SRC_DIR}
    ${PROP3_SRC_DIR}
    ${SCAENA_SRC_DIR}
    ${EXTH_OTS_DIR})
SET(SCAENA_QT_MODULES
    Widgets
    OpenGL)
