# Qt
FIND_PACKAGE(Qt5Core REQUIRED)
FIND_PACKAGE(Qt5Gui REQUIRED)
SET(CMAKE_AUTOMOC ON)


# Global
SET(PROP3_LIBRARIES
    ${CELLAR_PROJECT}
    ${MEDIA_PROJECT})
SET(PROP3_INCLUDE_DIR
    ${CELLAR_SRC_DIR}
    ${MEDIA_SRC_DIR}
    ${PROP3_SRC_DIR}
    ${EXTH_OTS_DIR})
SET(PROP3_QT_MODULES
    Core
    Gui)
