# Qt
FIND_PACKAGE(Qt4 REQUIRED)
SET(QT_DONT_USE_QTGUI TRUE)
INCLUDE(${QT_USE_FILE})


# Glew
FIND_PACKAGE(GLEW REQUIRED)
MESSAGE(STATUS "GLEW bin: ${GLEW_LIBRARY}")
MESSAGE(STATUS "GLEW inc: ${GLEW_INCLUDE_PATH}")


# Global
SET(PROP3_LIBRARIES
    CellarWorkbench
	${GLEW_LIBRARY}
    ${GLEW_LIBRARIES})
SET(PROP3_INCLUDE_DIR 
	${PROP3_INCLUDE_DIR} 
	${GLEW_INCLUDE_PATH})
