# Qt
FIND_PACKAGE(Qt5Core REQUIRED)
FIND_PACKAGE(Qt5Gui REQUIRED)
FIND_PACKAGE(Qt5Widgets REQUIRED)
SET(CMAKE_AUTOMOC ON)


# Global
SET(PROP3_LIBRARIES
    ${CELLAR_PROJECT})
SET(PROP3_INCLUDE_DIR
    ${EXPERIMETAL_THEATRE_SRC_DIR}
    ${EXTH_OTS_DIR})
SET(PROP3_QT_MODULES
    Core
    Gui
    Widgets)
