# Qt
FIND_PACKAGE(Qt5OpenGL REQUIRED)
SET(CMAKE_AUTOMOC ON)
SET(CMAKE_INCLUDE_CURRENT_DIR ON)


# ExTh
SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH}
    "${PROJECTNAME_SRC_DIR}/../ExperimentalTheatre/")
FIND_PACKAGE(ExperimentalTheatre REQUIRED)


# Global
SET(PROJECTNAME_LIBRARIES
    ${ExTh_LIBRARIES})
SET(PROJECTNAME_INCLUDE_DIRS
    ${PROJECTNAME_SRC_DIR}
    ${ExTh_INCLUDE_DIRS})
SET(PROJECTNAME_QT_MODULES
    OpenGL)
