# Qt
FIND_PACKAGE(Qt4 REQUIRED)
SET(QT_DONT_USE_QTGUI TRUE)
INCLUDE(${QT_USE_FILE})


# Glew
FIND_PACKAGE(GLEW REQUIRED)
MESSAGE(STATUS "GLEW bin: ${GLEW_LIBRARY}")
MESSAGE(STATUS "GLEW inc: ${GLEW_INCLUDE_PATH}")


# Global
SET(PROP2_LIBRARIES
    CellarWorkbench
	${QT_LIBRARIES}
    ${GLEW_LIBRARY})
SET(PROP2_INCLUDE_DIR 
	${PROP2_INCLUDE_DIR} 
	${GLEW_INCLUDE_PATH})