# Qt
FIND_PACKAGE(Qt4 REQUIRED)
INCLUDE(${QT_USE_FILE})


# Global
SET(PROP2_LIBRARIES
    CellarWorkbench
    MediaWorkbench
    ${QT_LIBRARIES})
SET(PROP2_INCLUDE_DIR
	${CELLAR_INCLUDE_DIR}
	${MEDIA_INCLUDE_DIR}
    ${PROP2_INCLUDE_DIR})
