# Qt
FIND_PACKAGE(Qt4 REQUIRED)
SET(QT_USE_QTOPENGL TRUE)
INCLUDE(${QT_USE_FILE})


# Glew
FIND_PACKAGE(GLEW REQUIRED)
MESSAGE(STATUS "GLEW bin: ${GLEW_LIBRARY}")
MESSAGE(STATUS "GLEW inc: ${GLEW_INCLUDE_PATH}")

# Global
SET(CELLAR_LIBRARIES
    ${QT_LIBRARIES}
    ${GLEW_LIBRARY})
SET(CELLAR_INCLUDE_DIR 
	${CELLAR_INCLUDE_DIR} 
	${GLEW_INCLUDE_PATH})
