# Qt
FIND_PACKAGE(Qt4 REQUIRED)
INCLUDE(${QT_USE_FILE})

# Freetype2
FIND_PACKAGE(Freetype REQUIRED)
MESSAGE(STATUS "Freetype version: ${FREETYPE_VERSION_STRING}")

# Global
SET(CELLAR_LIBRARIES
    ${QT_LIBRARIES}
    ${FREETYPE_LIBRARIES})
SET(CELLAR_INCLUDE_DIR 
    ${CELLAR_INCLUDE_DIR}
    ${FREETYPE_INCLUDE_DIRS})
