# Qt
FIND_PACKAGE(Qt5Core REQUIRED)
FIND_PACKAGE(Qt5Gui REQUIRED)
SET(CMAKE_AUTOMOC ON)

# Global
SET(CELLAR_LIBRARIES
    ${GL3_PROJECT})
SET(CELLAR_INCLUDE_DIR 
    ${EXPERIMETAL_THEATRE_SRC_DIR}
    ${EXTH_OTS_DIR})
SET(CELLAR_QT_MODULES
    Core
    Gui)
